add simple frontend, create attacks table and controller
yilativs/chtracker pull request #14
Opened 2021-03-30 20:28 UTC by itka4yk

2021-03-31 00:16 UTC, madamusinski requested changes

2021-03-31 00:16 UTC, madamusinski commented on src/main/java/org/chtracker/web/AttackController.java
> +    @Autowired
Unneccesary Annotation. Starting from Spring 4.3 it is ommited to use @Autowired over constructor injector

2021-03-31 00:16 UTC, madamusinski commented on src/main/java/org/chtracker/web/AttackController.java
> +        if (from == null && to == null) {
Logic like this with if ladder is responsibility of service/facade not a controller.

2021-03-31 18:49 UTC, itka4yk commented on src/main/java/org/chtracker/web/AttackController.java
> +    @Autowired
done

2021-03-31 18:49 UTC, itka4yk commented on src/main/java/org/chtracker/web/AttackController.java
> +        if (from == null && to == null) {
done

2021-03-31 21:13 UTC, itka4yk commented
Guys, feel free to comment UI/UX side, I will adjust everything.

![image](https://user-images.githubusercontent.com/14962653/113211948-6dbf9380-9276-11eb-8a40-b9e230b230b4.png)
![image](https://user-images.githubusercontent.com/14962653/113212051-8cbe2580-9276-11eb-8cd1-c918cee576aa.png)

2021-04-02 23:15 UTC, itka4yk commented
Create report form with used abortive treatments table.

This is editable table, which create new row after last one was edited.

![image](https://user-images.githubusercontent.com/14962653/113460626-b06da100-9419-11eb-886b-e18aa9c43458.png)
![image](https://user-images.githubusercontent.com/14962653/113460680-d5faaa80-9419-11eb-8103-bd9cbf172692.png)
![image](https://user-images.githubusercontent.com/14962653/113460686-e14dd600-9419-11eb-8108-857b7a6e1780.png)

No validation applied at this moment.

2021-04-04 08:09 UTC, closed without merging